### ISSUE TITLE
Missing ifdefs for UserConsentedAll?

### ISSUE THREAD

**Issue by pplcf** [binouze/GoogleUserMessagingPlatform#1]
> Library/PackageCache/com.binouze.googleusermessagingplatform@3367dccb33/Runtime/GoogleUserMessagingPlatform.cs(386,22): error CS0103: The name '_GetConsentForExternal' does not exist in the current context

It seems project won't compile for non-iOS target.

**Comment by binouze** [comment]
sorry just updated it, it should work now
