### ISSUE TITLE
An API question for SetOnStatusChangedListener

### ISSUE THREAD

**Issue by pplcf** [binouze/GoogleUserMessagingPlatform#2]
Is there a guarantee for SetOnStatusChangedListener to be called on every GoogleUserMessagingPlatform.Initialize? Or this status should be tracked & stored manually by design? 

At the moment I use it simply like this:

```
    private void Awake()
    {
        GoogleUserMessagingPlatform.SetOnStatusChangedListener( MajConsentStatus );
        GoogleUserMessagingPlatform.Initialize();
    }
```

```
    private void MajConsentStatus( ConsentStatus status )
    {
        GoogleUserMessagingPlatform.ShowFormIfRequired((required) =>
        {
            if (!required)
            {
                FindObjectOfType<GDPRSensitiveStuffHandler>().Init();
            }
        });
    }
```

I'm not sure if I should rely on SetOnStatusChangedListener to be called at every app startup. 
Could you please clarify on this?

**Comment by pplcf** [comment]
It seems UMP error states are not propagated to Unity layer hence SetOnStatusChangedListener might not be invoked in some situations.

**Comment by binouze** [comment]
Hi,
 
Yes sure, the status change listener should be called when initialisation complete.
As I don't use it in my app I never see any problem with it, I will make some tests.
If you have steps to reproduce the bug, it could be faster for me to fix it.

In case of errors during initialisation you should enable debug logging and look at android logcat logs. 
If your app and your form is configured, you shouldn't have any errors. 
In case of errors, the consent status have the default value (UNKNOWN). 
I'm open to suggestion on how to better handle errors ;)

**Comment by binouze** [comment]
Hi,
Just made an update, the listener should now be correctly called after Initialisation (even in case of errors).
Be sure to enable debug logs during tests to be sure everything is OK.

Just a note about your usage of the `GoogleUserMessagingPlatform.ShowFormIfRequired` callback value that seems incorrect:
It isn't a boolean indicating if the user accepted the conditions or if the form is required, it's just a boolean to know if the form has been presented to the user.

For a EU user, the first time he open the app, the ConsentStatus should be `REQUIRED`, 
in this case if you call `GoogleUserMessagingPlatform.ShowFormIfRequired`, the form will be shown to the user and the callback will return `true` (whether he accepts or not to share something).
After that, the ConsentStatus should be `OBTAINED` (even if the user deny all). 
All the next time you call `GoogleUserMessagingPlatform.ShowFormIfRequired`, the form will not be shown and the callback will returns `false`.

To know if the user is under GDPR regulation, you can use `GoogleUserMessagingPlatform.IsGDPRRequired` instead.


As the StatusChanged listener is now correctly called, I close the issue.

**Comment by pplcf** [comment]
> Just a note about your usage of the `GoogleUserMessagingPlatform.ShowFormIfRequired` callback value that seems incorrect:
> It isn't a boolean indicating if the user accepted the conditions or if the form is required, it's just a boolean to know if the form has been presented to the user.

Yeah, I use LevelPlay SDK and if to believe their documentation it will honor user permissions once they are acquired. So I need to prompt UMP before LevelPlay init.


Thanks for the great work, it saved me a lot of time.

**Comment by binouze** [comment]
I will push an update soon with an optional OnComplete callback on the Initialize() function, I think it would be better.
I'm currently testing if if everything is OK before to push it ;)
