### ISSUE TITLE
deleteOutdatedTCString: wrong timestamp parsing

### ISSUE THREAD

**Issue by Wnntyl** [binouze/GoogleUserMessagingPlatform#6]
Hi,
Starting from May 3, 2024, the consent window began to be shown every time our game starts. According to the logs, the deleteOutdatedTCString() method is triggered. It seems that now the timestamp is parsed incorrectly for some reason. Relevant only for new installs or reinstalls.
Perhaps the TCF String format has changed somehow?

```
2024/05/07 16:34:38.982 8842 8842 Info GoogleUMP GoogleUMP::Initialize
2024/05/07 16:34:38.983 8842 8842 Info GoogleUserMessagingPlatform::GDRPHelper GoogleUserMessagingPlatform::GDRPHelper:: deleteOutdatedTCString now = 1715085278983 - timestamp = 1609343539200 - daysAgo = 1223
2024/05/07 16:34:38.984 8842 8842 Info GoogleUMP GoogleUMP::deleted outdated TCF String
```

**Comment by binouze** [comment]
Thanks for the report, I'll try to see if there are changes in the TCF documentation about it.
I'll try to find if Google UMP take into account the outdated string now, as last time I had the problem was in the version 1.0, maybe they now handle outdated TCF datas correctly now.

**Comment by binouze** [comment]
After some reading of the Google [documentation](https://developers.google.com/admob/android/privacy/gdpr#how_to_read_consent_choices), I found:

> If a user has already made a consent decision, Google's consent management solution won't request to gather new consent until the TC string is expired or otherwise becomes invalid.

So, it seems that google UMP now takes care of the expired TCF strings. 
I will publish an update without this old fix.
